import type { PlayDef, Spot } from './plays';

const HOME: Spot = { base: 'home' };
const FIRST: Spot = { base: 'first' };
const SECOND: Spot = { base: 'second' };
const THIRD: Spot = { base: 'third' };
const MOUND: Spot = { base: 'mound' };
const BATTER_OUT: Spot = { at: [45, 45] };

const SPOTS = {
  leftShallow: { at: [228, -30] } as Spot,
  leftLine: { at: [260, -40] } as Spot,
  leftGap: { at: [322, -20] } as Spot,
  leftDeep: { at: [296, -26] } as Spot,
  leftWall: { at: [346, -28] } as Spot,
  leftCorner: { at: [332, -40] } as Spot,

  centerShallow: { at: [240, 0] } as Spot,
  centerMedium: { at: [280, 0] } as Spot,
  centerGapLeft: { at: [320, -10] } as Spot,
  centerGapRight: { at: [320, 10] } as Spot,
  centerDeep: { at: [334, 0] } as Spot,
  centerWall: { at: [352, 0] } as Spot,

  rightShallow: { at: [228, 28] } as Spot,
  rightLine: { at: [260, 40] } as Spot,
  rightGap: { at: [322, 18] } as Spot,
  rightDeep: { at: [296, 24] } as Spot,
  rightWall: { at: [346, 30] } as Spot,
  rightCorner: { at: [332, 40] } as Spot,

  cut3BHome: { at: [118, -20] } as Spot,
  cutSSLeft: { at: [182, -18] } as Spot,
  relaySSLeft: { at: [214, -18] } as Spot,
  relay2BLeft: { at: [196, 10] } as Spot,
  deep3B: { at: [146, -44] } as Spot,

  cut1BHome: { at: [120, 14] } as Spot,
  cutSSCenter: { at: [188, -8] } as Spot,
  relaySSCenter: { at: [212, -8] } as Spot,
  relay2BCenter: { at: [198, 12] } as Spot,
  deepHome: { at: [30, 192] } as Spot,

  cut2BRight: { at: [182, 14] } as Spot,
  relay2BRight: { at: [214, 16] } as Spot,
  deep1B: { at: [146, 44] } as Spot,

  buntThird: { at: [40, -18] } as Spot,
  buntFirst: { at: [38, 18] } as Spot,
  dribblerPlate: { at: [24, 182] } as Spot,
  passedBall: { at: [30, 154] } as Spot,
  passedBallFirst: { at: [24, 164] } as Spot,
  chopperMound: { at: [60, -4] } as Spot,
  slowRollerFirst: { at: [56, 34] } as Spot,
  slowRollerThird: { at: [56, -34] } as Spot,
  shortUpMiddle: { at: [150, 4] } as Spot,
  secondRight: { at: [148, 20] } as Spot,
  thirdHot: { at: [110, -36] } as Spot,
  firstHot: { at: [110, 36] } as Spot,
  plateFence: { at: [18, 214] } as Spot,
};

interface OutfieldMeta {
  prefix: string;
  label: 'LF' | 'CF' | 'RF';
  zone: string;
  shallow: Spot;
  line: Spot;
  gap: Spot;
  deep: Spot;
  wall: Spot;
  corner: Spot;
  cutHome: { label: string; spot: Spot };
  cutThird: { label: string; spot: Spot };
  relaySecond: { label: string; spot: Spot };
  backupHome: { label: string; spot: Spot };
  support: { label: string; spot: Spot };
  backupGap: { label: string; spot: Spot };
}

function makeRelayPlay(config: {
  id: string;
  name: string;
  situation: string;
  teaches: string;
  fielder: string;
  fieldSpot: Spot;
  batterTo?: Spot;
  runners?: { from: Spot; to?: Spot }[];
  cutoffs?: { label: string; spot: Spot }[];
  target: Spot;
  roles?: Record<string, string>;
  extraMoves?: Record<string, Spot>;
  category?: string;
}): PlayDef {
  return {
    id: config.id,
    name: config.name,
    situation: config.situation,
    category: config.category ?? 'Cutoffs and relays',
    teaches: config.teaches,
    roles: config.roles,
    batterTo: config.batterTo,
    runners: config.runners,
    moves: {
      [config.fielder]: config.fieldSpot,
      ...(config.extraMoves ?? {}),
      ...Object.fromEntries((config.cutoffs ?? []).map((cut) => [cut.label, cut.spot])),
    },
    ball: [
      HOME,
      { fielder: config.fielder },
      ...(config.cutoffs ?? []).map((cut) => ({ fielder: cut.label })),
      config.target,
    ],
  };
}

function makeFlyPlay(config: {
  id: string;
  name: string;
  situation: string;
  teaches: string;
  fielder: string;
  fieldSpot: Spot;
  runners?: { from: Spot; to?: Spot }[];
  cut?: { label: string; spot: Spot };
  target?: Spot;
  roles?: Record<string, string>;
  extraMoves?: Record<string, Spot>;
}): PlayDef {
  return {
    id: config.id,
    name: config.name,
    situation: config.situation,
    category: 'Fly balls',
    teaches: config.teaches,
    roles: config.roles,
    batterTo: BATTER_OUT,
    runners: config.runners,
    moves: {
      [config.fielder]: config.fieldSpot,
      ...(config.extraMoves ?? {}),
      ...(config.cut ? { [config.cut.label]: config.cut.spot } : {}),
    },
    ball: [
      HOME,
      { fielder: config.fielder },
      ...(config.cut ? [{ fielder: config.cut.label }] : []),
      ...(config.target ? [config.target] : []),
    ],
  };
}

function makeOutfieldSeries(meta: OutfieldMeta): PlayDef[] {
  return [
    makeRelayPlay({
      id: `${meta.prefix}-single-home`,
      name: `Single to ${meta.zone} — throw home`,
      situation: `Runner on second. Base hit to ${meta.zone}.`,
      teaches: 'Get it to the plate on a line through the cut man.',
      fielder: meta.label,
      fieldSpot: meta.deep,
      batterTo: FIRST,
      runners: [{ from: SECOND, to: HOME }],
      cutoffs: [meta.cutHome],
      target: HOME,
      roles: { C: 'Set up the plate early and receive the throw to finish the play.' },
      extraMoves: { [meta.backupHome.label]: meta.backupHome.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-single-third`,
      name: `Single to ${meta.zone} — throw to third`,
      situation: `Runner on first. Base hit to ${meta.zone}; he tries for third.`,
      teaches: 'Hit the relay early and keep the runner from taking the extra base.',
      fielder: meta.label,
      fieldSpot: meta.deep,
      batterTo: FIRST,
      runners: [{ from: FIRST, to: THIRD }],
      cutoffs: [meta.cutThird],
      target: THIRD,
      extraMoves: { [meta.support.label]: meta.support.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-hold-third`,
      name: `Single to ${meta.zone} — hold the runner at third`,
      situation: `Runner on second. Clean single to ${meta.zone}; keep him from scoring.`,
      teaches: 'Attack the ball and get it to third base before the runner commits home.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
      batterTo: FIRST,
      runners: [{ from: SECOND, to: THIRD }],
      target: THIRD,
      extraMoves: { [meta.support.label]: meta.support.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-batter-second`,
      name: `${meta.zone} hit — keep the batter at first`,
      situation: `Ball drops in ${meta.zone}. Batter thinks double out of the box.`,
      teaches: 'Come up throwing to second and make him stop there.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
      batterTo: SECOND,
      target: SECOND,
      extraMoves: { [meta.relaySecond.label]: meta.relaySecond.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-gap-second`,
      name: `${meta.zone} gap — relay to second`,
      situation: `Ball into the ${meta.zone} gap with the batter stretching the hit.`,
      teaches: 'Relay man goes out to meet the throw and keeps the double a double.',
      fielder: meta.label,
      fieldSpot: meta.gap,
      batterTo: SECOND,
      cutoffs: [meta.relaySecond],
      target: SECOND,
      extraMoves: { [meta.backupGap.label]: meta.backupGap.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-gap-third`,
      name: `${meta.zone} gap — relay to third`,
      situation: `Runner on first. Ball splits the ${meta.zone} gap and he is sent hard.`,
      teaches: 'Relay to third with pace and make the lead runner stop or slide.',
      fielder: meta.label,
      fieldSpot: meta.gap,
      batterTo: SECOND,
      runners: [{ from: FIRST, to: THIRD }],
      cutoffs: [meta.relaySecond],
      target: THIRD,
      extraMoves: { [meta.support.label]: meta.support.spot, [meta.backupGap.label]: meta.backupGap.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-off-wall-third`,
      name: `${meta.zone} off the wall — play the batter at third`,
      situation: `Drive one-hops the wall in ${meta.zone}. Batter pushes for third.`,
      teaches: 'Turn the wall ball into a clean relay and make third base the last bag.',
      fielder: meta.label,
      fieldSpot: meta.wall,
      batterTo: THIRD,
      cutoffs: [meta.relaySecond],
      target: THIRD,
      extraMoves: { [meta.support.label]: meta.support.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-off-wall-home`,
      name: `${meta.zone} off the wall — relay home`,
      situation: `Runner on second. Ball gets to the wall in ${meta.zone}.`,
      teaches: 'Get to where the carom goes and relay home through the middle.',
      fielder: meta.label,
      fieldSpot: meta.wall,
      batterTo: SECOND,
      runners: [{ from: SECOND, to: HOME }],
      cutoffs: [meta.relaySecond, meta.cutHome],
      target: HOME,
      roles: { C: 'Move up the line, show a target, and receive the relay at the plate.' },
      extraMoves: { [meta.backupHome.label]: meta.backupHome.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-cut-batter`,
      name: `${meta.zone} throw home — cut and get the batter`,
      situation: `Runner scores from second on a hit to ${meta.zone}; batter rounds first too far.`,
      teaches: 'If home has no chance, cut it and get the trail runner behind the run.',
      fielder: meta.label,
      fieldSpot: meta.deep,
      batterTo: SECOND,
      runners: [{ from: SECOND, to: HOME }],
      cutoffs: [meta.cutHome],
      target: SECOND,
    }),
    makeRelayPlay({
      id: `${meta.prefix}-charge-third`,
      name: `${meta.zone} flare — freeze the runner at third`,
      situation: `Runner on second. Soft liner into shallow ${meta.zone}.`,
      teaches: 'Charge it hard and throw through the cutoff to keep the runner at third.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
      batterTo: FIRST,
      runners: [{ from: SECOND, to: THIRD }],
      cutoffs: [meta.cutThird],
      target: THIRD,
    }),
    makeRelayPlay({
      id: `${meta.prefix}-corner-home`,
      name: `${meta.zone} corner ball — relay home`,
      situation: `Runner on second. Ball rolls all the way into the ${meta.zone} corner.`,
      teaches: 'Work the deepest ball on the field back to the plate without panicking.',
      fielder: meta.label,
      fieldSpot: meta.corner,
      batterTo: SECOND,
      runners: [{ from: SECOND, to: HOME }],
      cutoffs: [meta.relaySecond, meta.cutHome],
      target: HOME,
      roles: { C: 'Get to the plate and line up the long relay home.' },
      extraMoves: { [meta.backupHome.label]: meta.backupHome.spot },
    }),
    makeRelayPlay({
      id: `${meta.prefix}-corner-third`,
      name: `${meta.zone} corner ball — stop the lead runner at third`,
      situation: `Runner on first. Ball runs into the ${meta.zone} corner.`,
      teaches: 'Relay to third fast enough that the runner has to shut it down there.',
      fielder: meta.label,
      fieldSpot: meta.corner,
      batterTo: SECOND,
      runners: [{ from: FIRST, to: THIRD }],
      cutoffs: [meta.relaySecond],
      target: THIRD,
      extraMoves: { [meta.support.label]: meta.support.spot },
    }),
    makeFlyPlay({
      id: `${meta.prefix}-shallow-hold`,
      name: `Shallow ${meta.zone} fly — hold the runner`,
      situation: `Runner on third, less than two out. Shallow fly to ${meta.zone}.`,
      teaches: 'Catch it moving forward and come up ready to throw so the runner cannot tag.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
      runners: [{ from: THIRD }],
      target: HOME,
    }),
    makeFlyPlay({
      id: `${meta.prefix}-deep-tag-home`,
      name: `Deep ${meta.zone} fly — tag at home`,
      situation: `Runner on third. Deep fly to ${meta.zone}.`,
      teaches: 'Get behind the ball and throw home through the cut if the runner tags.',
      fielder: meta.label,
      fieldSpot: meta.deep,
      runners: [{ from: THIRD, to: HOME }],
      cut: meta.cutHome,
      target: HOME,
      roles: { C: 'Set your feet at the plate and be ready for the tag play.' },
      extraMoves: { [meta.backupHome.label]: meta.backupHome.spot },
    }),
    makeFlyPlay({
      id: `${meta.prefix}-tag-third`,
      name: `Deep ${meta.zone} fly — tag to third`,
      situation: `Runner on second. Catchable fly to ${meta.zone}.`,
      teaches: 'Make the catch and get the ball back to third before the runner steals ninety feet.',
      fielder: meta.label,
      fieldSpot: meta.deep,
      runners: [{ from: SECOND, to: THIRD }],
      cut: meta.cutThird,
      target: THIRD,
      extraMoves: { [meta.support.label]: meta.support.spot },
    }),
    makeFlyPlay({
      id: `${meta.prefix}-line-double`,
      name: `${meta.zone} line drive — double the runner off`,
      situation: `Runner on first. Liner caught in ${meta.zone} with the runner too far off.`,
      teaches: 'Secure the catch and throw behind the runner before he can recover.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
      runners: [{ from: FIRST, to: FIRST }],
      target: FIRST,
    }),
    makeFlyPlay({
      id: `${meta.prefix}-foul-line`,
      name: `${meta.zone} foul-line catch`,
      situation: `High pop drifting toward the ${meta.zone} line.`,
      teaches: 'Stay outside the ball and call it early so nobody else drifts under you.',
      fielder: meta.label,
      fieldSpot: meta.line,
    }),
    makeFlyPlay({
      id: `${meta.prefix}-gap-priority`,
      name: `${meta.zone} gap fly — take charge`,
      situation: `Fly ball splitting the ${meta.zone} side of the outfield.`,
      teaches: 'The outfielder with the better line calls it and the others peel off to back up.',
      fielder: meta.label,
      fieldSpot: meta.gap,
      roles: { [meta.backupGap.label]: 'Peel off and back up the catch in the gap.' },
      extraMoves: { [meta.backupGap.label]: meta.backupGap.spot },
    }),
    makeFlyPlay({
      id: `${meta.prefix}-do-or-die`,
      name: `${meta.zone} do-or-die catch — throw home`,
      situation: `Runner on third. Ball hangs in front of the ${meta.zone} outfielder.`,
      teaches: 'Charge through the ball so you are already moving toward the plate on the throw.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
      runners: [{ from: THIRD, to: HOME }],
      target: HOME,
      roles: { C: 'Own the plate and be ready to tag the runner coming from third.' },
    }),
    makeFlyPlay({
      id: `${meta.prefix}-blooper`,
      name: `${meta.zone} blooper — catch on the run`,
      situation: `Soft blooper falls between the infield and ${meta.zone}.`,
      teaches: 'Break in hard, keep the glove low, and take the easy out before it drops.',
      fielder: meta.label,
      fieldSpot: meta.shallow,
    }),
  ];
}

const MORE_OUTFIELD_PLAYS = [
  ...makeOutfieldSeries({
    prefix: 'lf',
    label: 'LF',
    zone: 'left',
    shallow: SPOTS.leftShallow,
    line: SPOTS.leftLine,
    gap: SPOTS.leftGap,
    deep: SPOTS.leftDeep,
    wall: SPOTS.leftWall,
    corner: SPOTS.leftCorner,
    cutHome: { label: '3B', spot: SPOTS.cut3BHome },
    cutThird: { label: 'SS', spot: SPOTS.cutSSLeft },
    relaySecond: { label: 'SS', spot: SPOTS.relaySSLeft },
    backupHome: { label: 'P', spot: SPOTS.deepHome },
    support: { label: '3B', spot: THIRD },
    backupGap: { label: 'CF', spot: SPOTS.centerGapLeft },
  }),
  ...makeOutfieldSeries({
    prefix: 'cf',
    label: 'CF',
    zone: 'centre',
    shallow: SPOTS.centerShallow,
    line: SPOTS.centerMedium,
    gap: SPOTS.centerGapLeft,
    deep: SPOTS.centerDeep,
    wall: SPOTS.centerWall,
    corner: SPOTS.centerGapRight,
    cutHome: { label: '1B', spot: SPOTS.cut1BHome },
    cutThird: { label: 'SS', spot: SPOTS.cutSSCenter },
    relaySecond: { label: 'SS', spot: SPOTS.relaySSCenter },
    backupHome: { label: 'P', spot: SPOTS.deepHome },
    support: { label: '3B', spot: THIRD },
    backupGap: { label: '2B', spot: SPOTS.relay2BCenter },
  }),
  ...makeOutfieldSeries({
    prefix: 'rf',
    label: 'RF',
    zone: 'right',
    shallow: SPOTS.rightShallow,
    line: SPOTS.rightLine,
    gap: SPOTS.rightGap,
    deep: SPOTS.rightDeep,
    wall: SPOTS.rightWall,
    corner: SPOTS.rightCorner,
    cutHome: { label: '1B', spot: SPOTS.cut1BHome },
    cutThird: { label: '2B', spot: SPOTS.cut2BRight },
    relaySecond: { label: '2B', spot: SPOTS.relay2BRight },
    backupHome: { label: 'P', spot: SPOTS.deepHome },
    support: { label: '3B', spot: THIRD },
    backupGap: { label: 'CF', spot: SPOTS.centerGapRight },
  }),
];

const MORE_CATCHER_AND_PITCHER_PLAYS: readonly PlayDef[] = [
  {
    id: 'catcher-bunt-first',
    name: 'Bunt to the catcher — out at first',
    situation: 'Drag bunt dies in front of the plate with only one play.',
    category: 'Bunt defense',
    teaches: 'Catcher gets out fast, sets his feet, and throws through the runner.',
    batterTo: FIRST,
    moves: { C: SPOTS.dribblerPlate, '1B': FIRST },
    ball: [HOME, { fielder: 'C' }, FIRST],
  },
  {
    id: 'catcher-bunt-home',
    name: 'Bunt to the catcher — force at home',
    situation: 'Runner on third. Bunt pops dead in front of the plate.',
    category: 'Bunt defense',
    teaches: 'The catcher has to read it first and take the sure out at the plate.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { C: SPOTS.dribblerPlate },
    ball: [HOME, { fielder: 'C' }, HOME],
  },
  {
    id: 'catcher-backpick-first',
    name: 'Catcher back-picks first',
    situation: 'Runner at first wanders off after the pitch.',
    category: 'Runners moving',
    teaches: 'Quick feet and a short throw beat the runner back to the bag.',
    runners: [{ from: { at: [98, 42] }, to: FIRST }],
    moves: { '1B': FIRST },
    ball: [MOUND, HOME, FIRST],
  },
  {
    id: 'catcher-backpick-second',
    name: 'Catcher back-picks second',
    situation: 'Runner on second gets lazy after taking the sign.',
    category: 'Runners moving',
    teaches: 'Middle infielders show late and the catcher throws right through the bag.',
    runners: [{ from: { at: [136, -6] }, to: SECOND }],
    moves: { SS: SECOND },
    ball: [MOUND, HOME, SECOND],
  },
  {
    id: 'catcher-throw-second',
    name: 'Catcher throws out a steal at second',
    situation: 'Runner on first breaks on first movement.',
    category: 'Runners moving',
    teaches: 'Catch, replace the feet, and throw over the top of the mound.',
    runners: [{ from: FIRST, to: SECOND }],
    moves: { SS: SECOND },
    ball: [MOUND, HOME, SECOND],
  },
  {
    id: 'catcher-throw-third',
    name: 'Catcher throws out a steal at third',
    situation: 'Runner on second goes early and the defence is ready for it.',
    category: 'Runners moving',
    teaches: 'Third baseman beats the runner there and the shortstop trails the throw.',
    runners: [{ from: SECOND, to: THIRD }],
    moves: { '3B': THIRD, SS: SPOTS.cutSSLeft },
    ball: [MOUND, HOME, THIRD],
  },
  {
    id: 'catcher-passed-ball-second',
    name: 'Passed ball — keep the runner at second',
    situation: 'Runner on first. Pitch skips away but does not get far.',
    category: 'Pitcher and catcher',
    teaches: 'Catcher recovers and comes up fast enough to stop the extra base.',
    runners: [{ from: FIRST, to: SECOND }],
    moves: { C: SPOTS.passedBallFirst, SS: SECOND },
    ball: [MOUND, SPOTS.passedBallFirst, SECOND],
  },
  {
    id: 'catcher-passed-ball-home',
    name: 'Passed ball — play at the plate',
    situation: 'Runner on third breaks as the ball kicks to the screen.',
    category: 'Pitcher and catcher',
    teaches: 'The catcher gets it and throws home while the pitcher returns to the plate.',
    runners: [{ from: THIRD, to: HOME }],
    moves: { C: SPOTS.passedBall, P: HOME },
    ball: [MOUND, SPOTS.passedBall, HOME],
  },
  {
    id: 'catcher-pop-fence',
    name: 'Pop-up at the backstop',
    situation: 'Foul ball climbs high and drifts to the fence behind home.',
    category: 'Fly balls',
    teaches: 'Turn, run, find it again, and catch it before you hit the fence.',
    batterTo: BATTER_OUT,
    moves: { C: SPOTS.plateFence },
    ball: [HOME, { fielder: 'C' }],
  },
  {
    id: 'catcher-dribbler-home',
    name: 'Dribbler in front — flip home',
    situation: 'Bases loaded. Soft roller stops halfway to the mound.',
    category: 'Double plays',
    teaches: 'Catcher attacks the ball and flips to the plate for the lead runner.',
    batterTo: FIRST,
    runners: [
      { from: THIRD, to: HOME },
      { from: SECOND, to: THIRD },
      { from: FIRST, to: SECOND },
    ],
    moves: { C: SPOTS.dribblerPlate },
    ball: [HOME, { fielder: 'C' }, HOME],
  },
  {
    id: 'pitcher-bunt-third',
    name: 'Pitcher fields the bunt and gets third',
    situation: 'Runners on first and second. Bunt is dead on the third-base side.',
    category: 'Bunt defense',
    teaches: 'Pitcher reads it early and gets the lead runner before everyone is safe.',
    batterTo: FIRST,
    runners: [
      { from: SECOND, to: THIRD },
      { from: FIRST, to: SECOND },
    ],
    moves: { P: SPOTS.buntThird, SS: THIRD, '2B': FIRST },
    ball: [HOME, { fielder: 'P' }, THIRD],
  },
  {
    id: 'pitcher-bunt-first',
    name: 'Pitcher fields the bunt and gets first',
    situation: 'Bunt rolls halfway up the first-base line with nobody forcing the lead runner.',
    category: 'Bunt defense',
    teaches: 'Take the sure out and trust the coverage at first.',
    batterTo: FIRST,
    moves: { P: SPOTS.buntFirst, '1B': FIRST },
    ball: [HOME, { fielder: 'P' }, FIRST],
  },
  {
    id: 'pitcher-cover-home-safety',
    name: 'Pitcher covers home on the infield single',
    situation: 'Runner on third. Soft grounder pulls the infield in.',
    category: 'Pitcher and catcher',
    teaches: 'As soon as the ball is in front, the pitcher breaks to the plate for the force.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { P: HOME, SS: SPOTS.shortUpMiddle },
    ball: [HOME, { fielder: 'SS' }, HOME],
  },
  {
    id: 'pitcher-backup-first-line',
    name: 'Pitcher backs up first on the line',
    situation: 'Ground ball hugs the first-base line and the throw may pull the fielder.',
    category: 'Pitcher and catcher',
    teaches: 'Pitcher never watches the play — he is behind first in case the throw gets away.',
    batterTo: FIRST,
    moves: { '1B': SPOTS.firstHot, P: SPOTS.deep1B },
    ball: [HOME, { fielder: '1B' }, FIRST],
  },
  {
    id: 'pitcher-backup-home-center',
    name: 'Pitcher backs up home from centre field',
    situation: 'Runner on second. Ball hit to centre and the throw comes to the plate.',
    category: 'Pitcher and catcher',
    teaches: 'Pitcher gets deep enough behind home to turn a miss into just one base.',
    batterTo: FIRST,
    runners: [{ from: SECOND, to: HOME }],
    moves: { CF: SPOTS.centerDeep, P: SPOTS.deepHome, '1B': SPOTS.cut1BHome },
    ball: [HOME, { fielder: 'CF' }, { fielder: '1B' }, HOME],
  },
  {
    id: 'pitcher-comebacker-second',
    name: 'Comebacker — start it at second',
    situation: 'Runner on first. Ground ball right back through the box.',
    category: 'Double plays',
    teaches: 'Pitcher turns, feeds second, and lets the bag man finish the turn.',
    batterTo: FIRST,
    runners: [{ from: FIRST, to: SECOND }],
    moves: { P: SPOTS.chopperMound, SS: SECOND, '1B': FIRST },
    ball: [HOME, { fielder: 'P' }, SECOND, FIRST],
  },
  {
    id: 'pitcher-comebacker-home',
    name: 'Comebacker — home to first',
    situation: 'Bases loaded. Soft comebacker gives the pitcher time to check the plate.',
    category: 'Double plays',
    teaches: 'Get the force at home first and let the catcher finish the play.',
    batterTo: FIRST,
    runners: [
      { from: THIRD, to: HOME },
      { from: SECOND, to: THIRD },
      { from: FIRST, to: SECOND },
    ],
    moves: { P: SPOTS.chopperMound, '1B': FIRST },
    ball: [HOME, { fielder: 'P' }, HOME, FIRST],
  },
  {
    id: 'pitcher-slow-roller-home',
    name: 'Slow roller — pitcher to the plate',
    situation: 'Runner on third. Chopper dies between home and the mound.',
    category: 'Routine outs',
    teaches: 'Pitcher goes bare-handed and flips home before the runner gets there.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { P: SPOTS.chopperMound },
    ball: [HOME, { fielder: 'P' }, HOME],
  },
  {
    id: 'pitcher-cover-first-right',
    name: 'Pitcher covers first on the right-side play',
    situation: 'Second baseman goes far to his glove side for a ground ball.',
    category: 'Routine outs',
    teaches: 'Any ball to the right side means the pitcher is already running to first.',
    batterTo: FIRST,
    moves: { '2B': SPOTS.secondRight, P: FIRST },
    ball: [HOME, { fielder: '2B' }, { fielder: 'P' }],
  },
  {
    id: 'pitcher-backup-second-center',
    name: 'Pitcher trails the throw to second',
    situation: 'Base hit to centre with the batter trying to stretch it.',
    category: 'Pitcher and catcher',
    teaches: 'Pitcher follows the throw to second in case it gets away from the cutoff.',
    batterTo: SECOND,
    moves: { CF: SPOTS.centerShallow, SS: SECOND, P: { at: [175, -2] } },
    ball: [HOME, { fielder: 'CF' }, SECOND],
  },
];

const MORE_INFIELD_AND_RUNNER_PLAYS: readonly PlayDef[] = [
  {
    id: 'wheel-third',
    name: 'Wheel play — out at third',
    situation: 'Corners charge on the bunt and the shortstop rotates to third.',
    category: 'Bunt defense',
    teaches: 'Rotation has to start before the bunt is even dead or the lead runner is safe.',
    batterTo: FIRST,
    runners: [
      { from: SECOND, to: THIRD },
      { from: FIRST, to: SECOND },
    ],
    moves: { '3B': SPOTS.buntThird, SS: THIRD, '2B': FIRST, P: SPOTS.buntThird },
    ball: [HOME, { fielder: '3B' }, THIRD],
  },
  {
    id: 'wheel-home',
    name: 'Wheel play — force at home',
    situation: 'Runner on third. Infield crashes a bunt dropped in front of the plate.',
    category: 'Bunt defense',
    teaches: 'The whole point of the wheel is to get the lead runner before he scores.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { P: SPOTS.buntFirst, C: HOME, '3B': SPOTS.buntThird, '1B': SPOTS.buntFirst },
    ball: [HOME, { fielder: 'P' }, HOME],
  },
  {
    id: 'first-third-daylight',
    name: 'First and third — daylight play',
    situation: 'Runners on the corners. Catcher catches the trail runner leaning.',
    category: 'Runners moving',
    teaches: 'Throw behind the runner at first only if the man at third cannot score on it.',
    runners: [
      { from: FIRST, to: FIRST },
      { from: THIRD },
    ],
    moves: { '1B': FIRST, P: HOME },
    ball: [MOUND, HOME, FIRST],
  },
  {
    id: 'first-third-cutoff',
    name: 'First and third — cut the throw and hold',
    situation: 'Trail runner steals and the man at third breaks late.',
    category: 'Runners moving',
    teaches: 'Middle infield takes the throw and throws it right back to stop the run.',
    runners: [
      { from: FIRST, to: SECOND },
      { from: THIRD },
    ],
    moves: { SS: SECOND, P: HOME },
    ball: [MOUND, HOME, SECOND, MOUND],
  },
  {
    id: 'delayed-double-steal',
    name: 'Delayed double steal',
    situation: 'Runners on first and third move after the catcher relaxes.',
    category: 'Runners moving',
    teaches: 'Stop the run first; the back runner only matters if the plate stays covered.',
    runners: [
      { from: FIRST, to: SECOND },
      { from: THIRD, to: HOME },
    ],
    moves: { SS: SECOND, P: HOME },
    ball: [HOME, MOUND, HOME],
  },
  {
    id: 'snap-throw-third',
    name: 'Pitchout and snap throw to third',
    situation: 'Runner on second creeps too far toward third before the pitch.',
    category: 'Runners moving',
    teaches: 'Sell the pitch, get the catcher out of his crouch, and fire straight through the bag.',
    runners: [{ from: SECOND, to: THIRD }],
    moves: { '3B': THIRD, SS: SPOTS.cutSSLeft },
    ball: [MOUND, HOME, THIRD],
  },
  {
    id: 'snap-throw-first',
    name: 'Pitchout and snap throw to first',
    situation: 'Runner on first is drifting after the look-in.',
    category: 'Runners moving',
    teaches: 'Quick exchange beats a runner who thinks the ball is headed back to the mound.',
    runners: [{ from: { at: [100, 42] }, to: FIRST }],
    moves: { '1B': FIRST },
    ball: [MOUND, HOME, FIRST],
  },
  {
    id: 'rundown-second-third',
    name: 'Rundown between second and third',
    situation: 'Runner gets hung out trying for too much on a ground ball.',
    category: 'Runners moving',
    teaches: 'Run him back to the bag he left and keep a defender behind the throw.',
    runners: [{ from: { at: [144, -24] }, to: SECOND }],
    moves: { SS: SECOND, '3B': THIRD, '2B': { at: [166, -2] } },
    ball: [THIRD, SECOND],
  },
  {
    id: 'squeeze-first-base',
    name: 'Safety squeeze — everybody takes the out at first',
    situation: 'Runner on third waits until the bunt is down before breaking.',
    category: 'Bunt defense',
    teaches: 'Once the runner hesitates, the defence can relax and bank the easy out.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { P: SPOTS.buntThird, '1B': FIRST, C: HOME },
    ball: [HOME, { fielder: 'P' }, FIRST],
  },
  {
    id: 'middle-crash-home',
    name: 'Middle infield crash — out at home',
    situation: 'Runner on third, corners back. Shortstop reads the chop and crashes late.',
    category: 'Routine outs',
    teaches: 'Late crash still works if the fielder comes under control and throws to the plate.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { SS: SPOTS.shortUpMiddle, C: HOME },
    ball: [HOME, { fielder: 'SS' }, HOME],
  },
  {
    id: '6-2-home',
    name: '6-2 — shortstop home',
    situation: 'Bases loaded. Ground ball to the shortstop with the infield in.',
    category: 'Double plays',
    teaches: 'Shortstop goes to the shortest out and the catcher comes up ready to relay.',
    batterTo: FIRST,
    runners: [
      { from: THIRD, to: HOME },
      { from: SECOND, to: THIRD },
      { from: FIRST, to: SECOND },
    ],
    moves: { SS: SPOTS.shortUpMiddle, C: HOME },
    ball: [HOME, { fielder: 'SS' }, HOME],
  },
  {
    id: '5-2-home',
    name: '5-2 — third base home',
    situation: 'Runner on third. Slow roller to third with the corners in.',
    category: 'Routine outs',
    teaches: 'Third baseman attacks and throws home before the runner can steal the plate.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { '3B': SPOTS.thirdHot, C: HOME },
    ball: [HOME, { fielder: '3B' }, HOME],
  },
  {
    id: '4-2-home',
    name: '4-2 — second base home',
    situation: 'Runner on third. Chopper to the second baseman with the infield in.',
    category: 'Routine outs',
    teaches: 'Second baseman comes through the ball and throws straight to the plate.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { '2B': SPOTS.secondRight, C: HOME },
    ball: [HOME, { fielder: '2B' }, HOME],
  },
  {
    id: '2-5-pick',
    name: '2-5 back-pick at third',
    situation: 'Runner takes a huge turn at third after a foul ball.',
    category: 'Runners moving',
    teaches: 'Catcher snaps the throw while the third baseman sneaks back to the bag.',
    runners: [{ from: { at: [52, -54] }, to: THIRD }],
    moves: { '3B': THIRD },
    ball: [HOME, THIRD],
  },
  {
    id: '2-4-backpick',
    name: '2-4 snap throw to second',
    situation: 'Runner at second relaxes after the catcher receives the pitch.',
    category: 'Runners moving',
    teaches: 'Quick transfer gives the middle infield a chance to steal an out.',
    runners: [{ from: { at: [140, 6] }, to: SECOND }],
    moves: { '2B': SECOND },
    ball: [HOME, SECOND],
  },
  {
    id: '3-6-tag',
    name: 'First baseman starts the tag play',
    situation: 'Runner on first. Hard ground ball to first with the bag uncovered.',
    category: 'Double plays',
    teaches: 'First baseman tags the runner and then starts the relay across the diamond.',
    batterTo: FIRST,
    runners: [{ from: FIRST, to: SECOND }],
    moves: { '1B': SPOTS.firstHot, SS: SECOND, P: FIRST },
    ball: [HOME, { fielder: '1B' }, SECOND, { fielder: 'P' }],
  },
  {
    id: '6-5-force',
    name: 'Shortstop starts the force at third',
    situation: 'Runners on first and second. Ground ball through the left side.',
    category: 'Double plays',
    teaches: 'Third base is the first out when the lead runner is still in front of you.',
    batterTo: FIRST,
    runners: [
      { from: SECOND, to: THIRD },
      { from: FIRST, to: SECOND },
    ],
    moves: { SS: SPOTS.shortUpMiddle, '3B': THIRD, '1B': FIRST },
    ball: [HOME, { fielder: 'SS' }, THIRD, FIRST],
  },
  {
    id: '4-1-cover',
    name: 'Second to pitcher covering first',
    situation: 'Second baseman ranges deep into short right field.',
    category: 'Routine outs',
    teaches: 'The pitcher covers first and shows a clear target while the fielder throws on the run.',
    batterTo: FIRST,
    moves: { '2B': { at: [176, 30] }, P: FIRST },
    ball: [HOME, { fielder: '2B' }, { fielder: 'P' }],
  },
  {
    id: '5-6-hole',
    name: 'Third baseman starts it in the hole',
    situation: 'Runner on first. Ground ball deep in the 5-6 hole.',
    category: 'Double plays',
    teaches: 'If third can get to it, shortstop still owns the bag and the first baseman stays ready.',
    batterTo: FIRST,
    runners: [{ from: FIRST, to: SECOND }],
    moves: { '3B': SPOTS.slowRollerThird, SS: SECOND, '1B': FIRST },
    ball: [HOME, { fielder: '3B' }, SECOND, FIRST],
  },
  {
    id: 'ss-flip-home',
    name: 'Shortstop flips home on the slow roller',
    situation: 'Runner on third. Slow roller toward short with the infield tight.',
    category: 'Routine outs',
    teaches: 'Come get the ball and use the short flip when there is no time for a full throw.',
    batterTo: FIRST,
    runners: [{ from: THIRD, to: HOME }],
    moves: { SS: SPOTS.shortUpMiddle, C: HOME },
    ball: [HOME, { fielder: 'SS' }, HOME],
  },
];

export const MORE_PLAYS: readonly PlayDef[] = [
  ...MORE_OUTFIELD_PLAYS,
  ...MORE_CATCHER_AND_PITCHER_PLAYS,
  ...MORE_INFIELD_AND_RUNNER_PLAYS,
];
